name: plugin
description: "TMDb plugin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  plugin_api:
    path: ../../plugin_api
  dart_eval: ^0.8.1

dev_dependencies:
  # Add dev dependencies for your plugin's development, if any.
